"""Blog management models for super admin portal."""
from datetime import datetime
from typing import List, Optional, Dict, Any, Literal
from bson import ObjectId
from pydantic import BaseModel, Field, ConfigDict
from app.models.common import TimestampMixin, PyObjectId


class BlogImage(BaseModel):
    """Blog image model with compression metadata."""
    url: str
    publicId: str
    width: int
    height: int
    bytes: int
    format: str
    altText: str = ""
    caption: str = ""
    order: int = 0  # For image ordering within blog
    
    # Compression metadata
    compressionRatio: Optional[int] = 0  # Percentage compression achieved
    originalSize: Optional[int] = None  # Original file size in bytes
    variants: Optional[Dict[str, str]] = {}  # Different size variants (thumbnail, mobile, etc.)
    
    # Upload metadata
    uploadedAt: datetime = Field(default_factory=datetime.utcnow)
    tags: List[str] = []  # Cloudinary tags for organization
    
    # Image type
    imageType: Literal["hero", "content", "featured", "workspace"] = "content"


class BlogContentBlock(BaseModel):
    """Individual content block within a blog post."""
    type: Literal["paragraph", "heading", "subheading", "image", "list", "quote"]
    content: str
    image: Optional[BlogImage] = None  # For image blocks
    listItems: Optional[List[str]] = None  # For list blocks
    level: Optional[int] = 1  # For headings (h1, h2, h3)
    
    # Styling options
    alignment: Literal["left", "center", "right", "justify"] = "left"
    isBold: bool = False
    isItalic: bool = False


class AssociatedWorkspace(BaseModel):
    """Workspace associated with blog for contextual linking."""
    workspaceId: PyObjectId
    slug: str
    displayName: str
    locality: str
    city: str
    
    # Images from workspace
    workspaceImages: List[BlogImage] = []
    
    # Link type
    linkType: Literal["featured", "related", "contextual"] = "related"
    
    # Display settings
    showInSidebar: bool = True
    showInContent: bool = False
    customDescription: Optional[str] = None


class SEOMetadata(BaseModel):
    """SEO metadata for blog optimization."""
    metaTitle: str
    metaDescription: str
    keywords: List[str] = []
    ogTitle: str
    ogDescription: str
    ogImage: Optional[str] = None
    twitterCard: str = "summary_large_image"
    twitterTitle: str
    twitterDescription: str
    twitterImage: Optional[str] = None
    canonicalUrl: str
    schemaMarkup: Optional[Dict[str, Any]] = None  # JSON-LD structured data
    autoGenerated: bool = True
    lastUpdated: datetime = Field(default_factory=datetime.utcnow)


class BlogSocialMetadata(BaseModel):
    """Social media sharing metadata."""
    facebookShareCount: int = 0
    twitterShareCount: int = 0
    linkedinShareCount: int = 0
    totalShares: int = 0
    lastShared: Optional[datetime] = None


class BlogAnalytics(BaseModel):
    """Blog analytics tracking."""
    viewCount: int = 0
    uniqueViewers: int = 0
    averageReadTime: Optional[float] = None  # in minutes
    bounceRate: Optional[float] = None  # percentage
    scrollDepth: Optional[float] = None  # percentage
    lastViewedAt: Optional[datetime] = None
    
    # Engagement metrics
    likes: int = 0
    comments: int = 0
    shares: int = 0
    
    # SEO metrics
    keywordRankings: Optional[Dict[str, int]] = None  # keyword -> position
    backlinks: int = 0


class BlogPost(TimestampMixin):
    """Main blog post model with comprehensive features."""
    blogId: PyObjectId = Field(default_factory=PyObjectId, alias="_id")
    authorId: PyObjectId  # Admin user ID
    
    # Basic information
    title: str
    slug: str
    excerpt: str = ""  # Short summary for listings
    featuredImage: Optional[BlogImage] = None
    
    # Content structure
    contentBlocks: List[BlogContentBlock] = []
    readingTime: Optional[int] = None  # in minutes
    
    # Categories and tags
    categories: List[str] = []
    tags: List[str] = []
    
    # Associated workspaces
    associatedWorkspaces: List[AssociatedWorkspace] = []
    
    # Publishing status
    status: Literal["draft", "pending_review", "published", "archived"] = "draft"
    publishedAt: Optional[datetime] = None
    scheduledFor: Optional[datetime] = None
    
    # SEO and visibility
    seoMetadata: Optional[SEOMetadata] = None
    socialMetadata: Optional[BlogSocialMetadata] = None
    
    # Analytics
    analytics: Optional[BlogAnalytics] = None
    
    # Content settings
    allowComments: bool = True
    isFeatured: bool = False
    isSticky: bool = False  # Sticky at top of blog listing
    
    # Metadata
    wordCount: int = 0
    lastEditedAt: datetime = Field(default_factory=datetime.utcnow)
    editorNotes: Optional[str] = None
    
    model_config = ConfigDict(populate_by_name=True)

    @property
    def is_published(self) -> bool:
        """Check if blog is currently published."""
        if self.status != "published":
            return False
        
        if self.scheduledFor and self.scheduledFor > datetime.utcnow():
            return False
            
        return True


# Request/Response models for API
class BlogCreateRequest(BaseModel):
    """Request model for creating a blog post."""
    title: str
    excerpt: Optional[str] = ""
    contentBlocks: Optional[List[BlogContentBlock]] = []
    categories: Optional[List[str]] = []
    tags: Optional[List[str]] = []
    featuredImage: Optional[BlogImage] = None
    associatedWorkspaceIds: Optional[List[str]] = []  # List of workspace IDs
    status: Literal["draft", "pending_review", "published"] = "draft"
    scheduledFor: Optional[datetime] = None
    allowComments: Optional[bool] = True
    isFeatured: Optional[bool] = False


class BlogUpdateRequest(BaseModel):
    """Request model for updating a blog post."""
    title: Optional[str] = None
    excerpt: Optional[str] = None
    contentBlocks: Optional[List[BlogContentBlock]] = None
    categories: Optional[List[str]] = None
    tags: Optional[List[str]] = None
    featuredImage: Optional[BlogImage] = None
    associatedWorkspaceIds: Optional[List[str]] = None
    status: Optional[Literal["draft", "pending_review", "published", "archived"]] = None
    scheduledFor: Optional[datetime] = None
    allowComments: Optional[bool] = None
    isFeatured: Optional[bool] = None
    isSticky: Optional[bool] = None
    editorNotes: Optional[str] = None


class BlogListResponse(BaseModel):
    """Response model for listing blog posts."""
    blogs: List[BlogPost]
    total: int
    page: int
    limit: int
    totalPages: int


class BlogImageUploadResponse(BaseModel):
    """Response model for blog image upload."""
    image: BlogImage
    tempPublicId: str  # Temporary ID for draft state


class WorkspaceSelectionOption(BaseModel):
    """Option for workspace selection in blog editor."""
    workspaceId: str
    displayName: str
    slug: str
    locality: str
    city: str
    heroPhotos: List[BlogImage] = []
    isAvailable: bool = True


class BlogSEOUpdateRequest(BaseModel):
    """Request model for updating SEO metadata."""
    metaTitle: Optional[str] = None
    metaDescription: Optional[str] = None
    keywords: Optional[List[str]] = None
    ogTitle: Optional[str] = None
    ogDescription: Optional[str] = None
    ogImage: Optional[str] = None
    twitterTitle: Optional[str] = None
    twitterDescription: Optional[str] = None
    twitterImage: Optional[str] = None
    canonicalUrl: Optional[str] = None


class BlogPublishRequest(BaseModel):
    """Request model for publishing a blog."""
    publishNow: bool = True
    scheduledFor: Optional[datetime] = None
    sendNotifications: bool = True
    socialMediaShare: bool = False