"""SEO metadata generation and management service."""
from typing import Dict, List, Optional
from datetime import datetime
from bson import ObjectId

from app.db.mongodb import get_database
from app.models.premium_listing import SEOMetadata
from app.core.config import get_settings
from app.core.errors import NotFoundError


settings = get_settings()


def generate_listing_seo(listing: dict) -> SEOMetadata:
    """
    Auto-generate SEO metadata from listing data.
    
    Args:
        listing: The listing document from database
        
    Returns:
        SEOMetadata object with auto-generated fields
    """
    # Extract basic info
    display_name = listing.get("displayName", "")
    overview = listing.get("overview", "")
    locality = listing.get("location", {}).get("locality", "")
    city = listing.get("location", {}).get("city", "Delhi")
    amenities = listing.get("amenities", [])
    slug = listing.get("slugData", {}).get("slug", "")
    
    # Get first hero photo for OG/Twitter images
    hero_photos = listing.get("heroPhotos", [])
    og_image = hero_photos[0]["url"] if hero_photos and len(hero_photos) > 0 else None
    
    # Generate meta title (60 chars max for SEO)
    meta_title = f"{display_name} | Coworking Space in {locality}, {city} | Kosmix Spaces"
    if len(meta_title) > 60:
        # Truncate if too long
        meta_title = f"{display_name} | {locality} | Kosmix Spaces"
    
    # Generate meta description (155 chars max for SEO)
    # Use overview text, truncate intelligently
    meta_description = overview[:152] + "..." if len(overview) > 155 else overview
    if not meta_description:
        meta_description = f"Verified coworking space in {locality}, {city}. "
        if amenities:
            meta_description += f"Amenities: {', '.join(amenities[:3])}."
    
    # Ensure description doesn't exceed 155 chars
    if len(meta_description) > 155:
        meta_description = meta_description[:152] + "..."
    
    # Generate keywords
    keywords = [
        f"coworking space {locality}",
        f"office space {city}",
        display_name.lower(),
        locality.lower(),
        city.lower(),
        "coworking",
        "workspace",
        "office space"
    ]
    
    # Add amenities as keywords
    keywords.extend([amenity.lower() for amenity in amenities[:5]])
    
    # Add offering types that are enabled
    offerings = listing.get("offerings", {})
    for offering_type, offering_data in offerings.items():
        if offering_data.get("enabled"):
            offering_name = offering_type.replace("-", " ")
            keywords.append(offering_name)
    
    # Remove duplicates and limit to 15 keywords
    keywords = list(dict.fromkeys(keywords))[:15]
    
    # Generate canonical URL
    canonical_url = f"{settings.SITE_URL}/spaces{slug}"
    
    # OG Title (slightly different, can be longer)
    og_title = f"{display_name} - Coworking Space in {locality}, {city}"
    
    # OG Description (can be slightly longer than meta)
    og_description = overview[:200] if overview else meta_description
    
    # Twitter uses same as OG
    twitter_title = og_title
    twitter_description = og_description
    twitter_image = og_image
    
    return SEOMetadata(
        metaTitle=meta_title,
        metaDescription=meta_description,
        keywords=keywords,
        ogTitle=og_title,
        ogDescription=og_description,
        ogImage=og_image,
        twitterCard="summary_large_image",
        twitterTitle=twitter_title,
        twitterDescription=twitter_description,
        twitterImage=twitter_image,
        canonicalUrl=canonical_url,
        autoGenerated=True,
        lastUpdated=datetime.utcnow()
    )


async def update_listing_seo(listing_id: str, seo_data: Optional[Dict] = None) -> SEOMetadata:
    """
    Update or regenerate SEO metadata for a listing.
    
    Args:
        listing_id: The listing ID
        seo_data: Optional custom SEO data. If None, auto-generates from listing.
        
    Returns:
        Updated SEOMetadata object
        
    Raises:
        NotFoundError: If listing not found
    """
    db = get_database()
    
    # Get the listing
    listing = await db.premium_listings.find_one({"_id": ObjectId(listing_id)})
    if not listing:
        raise NotFoundError(f"Listing {listing_id} not found")
    
    # Generate or use provided SEO data
    if seo_data:
        # Custom SEO data provided
        seo_metadata = SEOMetadata(**seo_data)
        seo_metadata.autoGenerated = False
        seo_metadata.lastUpdated = datetime.utcnow()
    else:
        # Auto-generate from listing
        seo_metadata = generate_listing_seo(listing)
    
    # Update in database
    await db.premium_listings.update_one(
        {"_id": ObjectId(listing_id)},
        {
            "$set": {
                "seoMetadata": seo_metadata.model_dump(),
                "updatedAt": datetime.utcnow()
            }
        }
    )
    
    return seo_metadata


async def get_listing_seo(listing_id: str) -> Optional[SEOMetadata]:
    """
    Get SEO metadata for a listing.
    
    Args:
        listing_id: The listing ID
        
    Returns:
        SEOMetadata object or None if not found
    """
    db = get_database()
    
    listing = await db.premium_listings.find_one(
        {"_id": ObjectId(listing_id)},
        {"seoMetadata": 1}
    )
    
    if not listing or "seoMetadata" not in listing:
        return None
    
    return SEOMetadata(**listing["seoMetadata"])


async def ensure_listing_has_seo(listing_id: str) -> SEOMetadata:
    """
    Ensure a listing has SEO metadata. Generate if missing.
    
    Args:
        listing_id: The listing ID
        
    Returns:
        SEOMetadata object (existing or newly generated)
    """
    # Check if SEO exists
    seo = await get_listing_seo(listing_id)
    
    if seo:
        return seo
    
    # Generate and save SEO
    return await update_listing_seo(listing_id)


async def regenerate_all_listing_seo() -> int:
    """
    Regenerate SEO for all published listings.
    Useful for bulk updates or migrations.
    
    Returns:
        Number of listings updated
    """
    db = get_database()
    
    # Find all published listings
    listings = await db.premium_listings.find({
        "isPublished": True,
        "verificationStatus": {"$in": ["APPROVED", "APPROVED_VERIFIED"]}
    }).to_list(length=None)
    
    count = 0
    for listing in listings:
        try:
            await update_listing_seo(str(listing["_id"]))
            count += 1
        except Exception as e:
            print(f"Error updating SEO for listing {listing['_id']}: {e}")
    
    return count



